---
title: Meeting of South West RSE's in Bristol
padlet: https://uob.padlet.org/racheltunnicliffe1/rse-south-west-discussion-esqgnrwbo8d39r4i
---

Monday 23 June 2025, 9:30am – 3:30pm (refreshments from 9:30am for a 10am start)<br>
Room LG.02, [Fry Building, Woodland Road, Bristol, BS8 1UG](https://maps.google.com/?q=Fry Building, Woodland Road, Bristol, BS8 1UG) ([How to get here](https://www.bristol.ac.uk/maps/how-to-get-here/))

[Registration is closed](){.btn .disabled}

::: {.content-hidden}
[Register and/or submit a talk](https://forms.office.com/e/1fF8uhB1Tb){.btn .btn-primary}

Deadline for submission of talks
: Wednesday 28 May

Deadline to register as an attendee
: Sunday 8 June
:::

## Purpose

Following a successful event at the Met Office in February, the University of Bristol is hosting a further meeting on Monday 23 June.
It will be another day to **showcase interesting topics, share knowledge and build networks**.
It aims to complement the annual RSE conference and be useful to those in the South West / GW4 who are not part of a larger RSE group.

All are welcome, whether or not you are from the South West of the UK, and whether or not you [self-define as a Research Software Engineer (RSE)](https://society-rse.org/what-is-an-rse/).

## Agenda

<table class="table">
  <tr>
    <th>09:30
    <td>Refreshments on arrival
  <tr>
    <th>10:00
    <td><strong>Welcome</strong><br>
      <em>James Thomas, Rachel Tunnicliffe, Rita Rasteiro, Léo Gorman</em>
      <ul>
        <li>Introductions from the different groups attending
        <li>Getting your views on RSECon25
        <li>Introduction to [Padlet for the afternoon discussion session]({{< meta padlet >}})
      </ul>
  <tr>
    <th>10:30
    <td><strong>Keynote</strong><br>
      <em>Fliss Guest</em><br>
      Vice President of the Society of Research Software Engineering<br>
      Deputy Head of Research Software Engineering at the University of Exeter
  <tr>
    <th>11:10
    <td>Networking and refreshments
  <tr>
    <th rowspan="2">11:30
    <th>Session 1: Groups and facilities
  <tr>
    <td>[How can Universities / or Scientific centres support RSEs to deliver and share better research software?](https://padlet.com/pollyeccleston1/rse-sw-how-can-universities-or-scientific-centres-support-rs-eii7qg000a3hxz1z)<br>
      <em>Polly Eccleston</em>
  <tr>
    <th rowspan="4">11:50
    <th>Lightning talks (5 minutes)
  <tr>
    <td>Research IT Facility at the University of Bristol<br>
      <em>Serena Cooper</em>
  <tr>
    <td>Developing & Deploying Conceptual Design Tools for Factory Planning<br>
      <em>Lewis Gilbert</em>
  <tr>
    <td>The Isambard supercomputers<br>
      <em>Matt Williams</em>
  <tr>
    <th>12:25
    <td>Group photo
  <tr>
    <th>12:30
    <td>Lunch and optional walk/viewing tower
  <tr>
    <th>13:40
    <td><strong>Start of afternoon session</strong>
      <ul>
        <li>Work on [Padlet for the afternoon discussion session]({{< meta padlet >}})
  <tr>
    <th rowspan="2">13:45
    <th>Session 2: Applications
  <tr>
    <td>Mapping the March: an RSE's adventures in time and space<br>
      <em>Mike Jones</em>
  <tr>
    <th rowspan="4">14:05
    <th>Lightning talks (5 minutes)
  <tr>
    <td>How do you host translated content within a Django application?<br>
      <em>Benjamin O'Driscoll</em>
  <tr>
    <td>Support for the Python array API standard in SciPy<br>
      <em>Jake Bowhay</em>
  <tr>
    <td>Make `make` great again<br>
      <em>James Frost</em>
  <tr>
    <th>14:35
    <td>Networking and refreshments
  <tr>
    <th>14:50
    <td><strong>Discussion session</strong> ([Padlet link]({{< meta padlet >}}))<br>
      <em>Rachel Tunnicliffe</em>
      <ul>
        <li>The future of RSE South West events
        <li>RSE groups and how they're organised
        <li>RSE best practices
      </ul>
  <tr>
    <th>15:20
    <td><strong>Closing remarks</strong><br>
      <em>James Thomas, Rachel Tunnicliffe, Rita Rasteiro, Léo Gorman</em>
      <ul>
        <li>Feedback
  <tr>
    <th>15:30
    <td><strong>End of day</strong> and optional pub trip
</table>

## Code of conduct

All participants are expected to adhere to the [Society of RSE code of conduct for events](https://society-rse.org/about/policies/code-of-conduct/).

## Contact the organisers and other attendees

The easiest way to communicate with everyone is via the [#rse-south-west](https://ukrse.slack.com/archives/C085EGAULJ3) channel on the [UK RSE Slack instance](https://ukrse.slack.com/signup?redir=/archives/C085EGAULJ3).

If you would rather send us an email, please contact: <rse-south-west-2025@bristol.ac.uk>.
